### ISSUE TITLE
[BUG]  Error code 1: You are not eligible to get the lucky pot because you do not reach 15mb of sharing bandwich everyday

### ISSUE THREAD

**Issue by taylorhill0413** [gorouflex/HoneygainPot#7]
How to fix error  Error code 1: You are not eligible to get the lucky pot because you do not reach 15mb of sharing bandwich everyday

**Comment by gorouflex** [comment]
Good morning have you checked your earnings process like this?
[image](https://github.com/gorouflex/HoneygainPot/assets/98001973/2aeb05c6-7584-403e-ba6b-694cb0ac2adf)
You should earn at least 15mb everyday to get a lucky pot

**Comment by gorouflex** [comment]
@taylorhill0413 For more information check [here](https://github.com/gorouflex/Sandy/blob/main/Docs/HoneygainPot/Debug.md)

**Comment by gorouflex** [comment]
![IMG_0236](https://github.com/gorouflex/HoneygainPot/assets/98001973/f45f912f-f9ce-4c39-9dd7-b05942f6827b)

This is what happened when you shared enough 15mb everyday so the script can automatically claims your lucky pot
@taylorhill0413

**Comment by gorouflex** [comment]
Common issue, waited too long for response
Please refer at: https://github.com/gorouflex/Sandy/blob/main/Docs/HoneygainPot/Debug.md
@taylorhill0413
